(in-package #:cl-hamt)

;; Utility functions for operating on HAMTs.
(declaim (inline get-bits get-index vec-insert vec-remove vec-update))

(declaim (inline %u32 %u64 %rotl32 %rotl64))

(defun %u32 (x)
  (ldb (byte 32 0) x))

(defun %u64 (x)
  (ldb (byte 64 0) x))

(defun %rotl32 (x r)
  (declare (type (unsigned-byte 32) x)
           (type fixnum r))
  (%u32 (logior (ash x r)
                (ash x (- r 32)))))

(defun %rotl64 (x r)
  (declare (type (unsigned-byte 64) x)
           (type fixnum r))
  (%u64 (logior (ash x r)
                (ash x (- r 64)))))

(defun xxhash32-object (obj &optional (seed 0))
  "xxHash32 over the 32-bit sxhash representation of OBJ."
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type (unsigned-byte 32) seed))
  (let* ((prime2 #x85EBCA77)
         (prime3 #xC2B2AE3D)
         (prime4 #x27D4EB2F)
         (prime5 #x165667B1)
         (x (%u32 (sxhash obj)))
         (h (%u32 (+ seed prime5 4))))
    (setf h (%u32 (+ h (%u32 (* x prime3)))))
    (setf h (%u32 (* (%rotl32 h 17) prime4)))
    (setf h (logxor h (ash h -15)))
    (setf h (%u32 (* h prime2)))
    (setf h (logxor h (ash h -13)))
    (setf h (%u32 (* h prime3)))
    (setf h (logxor h (ash h -16)))
    h))

(defun siphash32-object (obj)
  "SipHash-2-4 over the 64-bit sxhash representation of OBJ, truncated to 32-bit."
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let* ((k0 #x0706050403020100)
         (k1 #x0f0e0d0c0b0a0908)
         (v0 (logxor #x736f6d6570736575 k0))
         (v1 (logxor #x646f72616e646f6d k1))
         (v2 (logxor #x6c7967656e657261 k0))
         (v3 (logxor #x7465646279746573 k1))
         (m (%u64 (sxhash obj))))
    (labels ((sipround ()
               (setf v0 (%u64 (+ v0 v1)))
               (setf v1 (%rotl64 v1 13))
               (setf v1 (logxor v1 v0))
               (setf v0 (%rotl64 v0 32))
               (setf v2 (%u64 (+ v2 v3)))
               (setf v3 (%rotl64 v3 16))
               (setf v3 (logxor v3 v2))
               (setf v0 (%u64 (+ v0 v3)))
               (setf v3 (%rotl64 v3 21))
               (setf v3 (logxor v3 v0))
               (setf v2 (%u64 (+ v2 v1)))
               (setf v1 (%rotl64 v1 17))
               (setf v1 (logxor v1 v2))
               (setf v2 (%rotl64 v2 32)))
             (siphash-compress (block)
               (setf v3 (logxor v3 block))
               (sipround)
               (sipround)
               (setf v0 (logxor v0 block))))
      (siphash-compress m)
      (siphash-compress (ash 8 56))
      (setf v2 (logxor v2 #xff))
      (sipround)
      (sipround)
      (sipround)
      (sipround)
      (%u32 (logxor v0 v1 v2 v3)))))

(defun resolve-hash-function (hash hash-mode)
  "Resolve a hash function from explicit HASH or HASH-MODE.
HASH-MODE values: :FAST (xxHash32, default), :SECURE (SipHash-2-4)."
  (cond
    (hash (ctypecase hash
            (function hash)
            (symbol (symbol-function hash))))
    ((or (null hash-mode) (eq hash-mode :fast))
     #'xxhash32-object)
    ((eq hash-mode :secure)
     #'siphash32-object)
    (t (error "Unknown hash mode ~S (expected :FAST or :SECURE)." hash-mode))))

(defun get-bits (hash depth)
  "Extract bits 5*depth : 5*(depth+1) from the number hash."
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type (unsigned-byte 32) hash)
           (type fixnum depth))
  (ldb (byte 5 (* 5 depth)) hash))

(defun get-index (bits bitmap)
  "Given the 5-bit int extracted from a hash at the present depth, find
the index in the current array corresponding to this bit sequence."
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type fixnum bits)
           (type (unsigned-byte 32) bitmap))
  (logcount (ldb (byte bits 0) bitmap)))

(defun vec-insert (vec pos item)
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type simple-vector vec)
           (type fixnum pos))
  (let* ((old-len (length vec))
         (len (1+ old-len))
         (v (make-array len)))
    (declare (type fixnum old-len len)
             (type simple-vector v))
    (replace v vec :end1 pos :end2 pos)
    (setf (svref v pos) item)
    (replace v vec :start1 (1+ pos) :start2 pos)
    v))

(defun vec-remove (vec pos)
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type simple-vector vec)
           (type fixnum pos))
  (let* ((old-len (length vec))
         (len (1- old-len))
         (v (make-array len)))
    (declare (type fixnum old-len len)
             (type simple-vector v))
    (replace v vec :end1 pos :end2 pos)
    (replace v vec :start1 pos :start2 (1+ pos))
    v))

(defun vec-update (vec pos item)
  (declare (optimize (speed 3) (safety 0) (debug 0))
           (type simple-vector vec)
           (type fixnum pos))
  (let ((v (copy-seq vec)))
    (declare (type simple-vector v))
    (setf (svref v pos) item)
    v))
